name: Test gha-k8s-deploy

on:
  - push

jobs:
  test-gha-k8s-deploy:
    runs-on: ubuntu-latest
    name: Test gha-k8s-deploy
    steps:
      - name: Export Environment Variables
        uses: dmsi-io/gha-env-variables@v1
        with:
          TLD: ${{ secrets.TOP_LEVEL_DOMAIN }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Kubernetes
        uses: dmsi-io/gha-k8s-deploy@feature/KNOX-176
        with: 
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GKE_CLUSTER_NAME: ${{ secrets.GCP_STAGING_CLUSTER_NAME }}
          GCP_ZONE: ${{ secrets.GCP_ZONE }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          skip_docker: 'true'